# Generated by Django 5.1 on 2025-01-30 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100)),
                ('Category_image', models.ImageField(upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Collection_image', models.ImageField(upload_to='Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Most_Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_image', models.ImageField(upload_to='Popular')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_description', models.CharField(max_length=9000)),
                ('Availability', models.CharField(max_length=500)),
                ('Stock', models.IntegerField()),
                ('Price', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quote', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_type', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('House_No', models.CharField(max_length=50)),
                ('Area_Colony', models.CharField(max_length=50)),
                ('Landmark', models.CharField(max_length=50)),
                ('Pincode', models.BigIntegerField()),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Contact', models.BigIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.BigIntegerField()),
                ('contact', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Date', models.DateField()),
                ('Duration', models.IntegerField()),
                ('Payment_Confirmation', models.IntegerField()),
                ('Cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.cart')),
                ('Delivery_Address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.address')),
                ('Payment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=50)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Cartitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Cart_Total', models.BigIntegerField()),
                ('Cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='MHS_app.cart')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(upload_to='Image')),
                ('product_variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.product_variation')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.CharField(max_length=50)),
                ('Ratings', models.IntegerField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.customer')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Category_Name', models.CharField(max_length=200, null=True)),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='MHS_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.subcategory'),
        ),
        migrations.CreateModel(
            name='Variation_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.variation')),
            ],
        ),
        migrations.AddField(
            model_name='product_variation',
            name='option_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.variation_option'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHS_app.product')),
            ],
        ),
    ]
