# Generated by Django 5.1 on 2025-02-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MHS_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Sub_category_id',
            new_name='Sub_category',
        ),
    ]
