# Generated by Django 5.1 on 2025-02-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MHS_app', '0002_rename_sub_category_id_product_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Availability',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Stock',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Sub_category',
            new_name='sub_category',
        ),
    ]
