# Generated by Django 5.1 on 2025-02-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MHS_app', '0003_rename_availability_product_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availability',
            new_name='Availability',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='Product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='Stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='Sub_category_id',
        ),
    ]
