# Generated by Django 5.1 on 2025-02-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MHS_app', '0004_rename_availability_product_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Sub_category_id',
            new_name='SubCategory',
        ),
    ]
