# Generated by Django 5.1 on 2025-02-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MHS_app', '0005_rename_sub_category_id_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SubCategory',
            new_name='Sub_category_id',
        ),
    ]
