# Generated by Django 5.1 on 2025-02-05 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHS_app', '0006_rename_subcategory_product_sub_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='MHS_app.subcategory'),
        ),
    ]
