# Generated by Django 5.2.8 on 2025-11-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MHS_app', '0007_yourmodel_alter_product_sub_category_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
